@startuml
title Sequence diagram:\nCreate member
participant Program
participant "controller::Application"
participant "controller::Member"
participant "view::Member"
participant "model::Member"

Program -> "controller::Application": Run()
"controller::Application" -> "view::Console": DisplayInstructions()
"controller::Application" -> "view::Console": GetEvent()
"controller::Application" -> "controller::Member": CreateMember()
"controller::Member" -> "view::Member": WantsToCreateNewMember()
"view::Member" -> "view::Member": GetFullName()
"view::Member" -> "view::Member": GetPersonalNumber()
"view::Member" -> "view::Member": CheckPersonalNumber(pNum)
"view::Member" -> "view::Member": CheckInputFieldForContent(pNum)
"view::Member" -> "view::Member": CheckInputFieldForContent(name)
"controller::Member" -> "model::Member": MemberExist(pNum)

alt MemberExist() = false
    "controller::Member" -> "model::Member": GenerateUniqueMemberId()
    "controller::Member" -> "model::Member": CreateNewMember(name, pNum, uMemberId)
    "model::Member" -> "model::Member": WriteToJsonFile(memberJsonObj)
    "controller::Member" -> "view::Member": NewMemberCreated()
else MemberExist() = true
    "controller::Member" -> "view::Member": MemberAlreadyExist()
end
@enduml
