@startuml
title Sequence diagram:\nChange member info
participant Program
participant Application << (C,#ADD1B2) >>
participant Console << (V,#FFE6E6) >>
participant Database << (M,#CCE6FF) >>

Program -> Application: Run()
Application -> Console: DisplayInstructions()
Application -> Console: GetEvent()
Application -> Console: WantsToChangeMemberInfo()
Application -> Database: MemberExist(name, pNum)

alt MemberExist() = true
    Database -> Database: ChangeMemberInfo(name, pNum)
    Application -> Console: MemberInfoUpdated()
else MemberExist() = false
    Application -> Console: MemberDoesNotExist()
end
@enduml
