@startuml
title Sequence diagram:\nChange boat info
participant Program
participant Application << (C,#ADD1B2) >>
participant Console << (V,#FFE6E6) >>
participant Database << (M,#CCE6FF) >>

Program -> Application: Run()
Application -> Console: DisplayInstructions()
Application -> Console: GetEvent()
Application -> Console: WantsToChangeBoatInfo()
Application -> Database: MemberExist(name, pNum)

alt MemberExist() = true
    Database -> Database: ChangeBoatInfo(type, length)
    Application -> Console: BoatInfoUpdated()
else MemberExist() = false
    Application -> Console: MemberDoesNotExist()
end
@enduml
