@startuml
title Sequence diagram:\nLook at member info
participant Program
participant "controller::Application"
participant "controller::Member"
participant "view::Console"
participant "model::Database"

Program -> "controller::Application": Run()
"controller::Application" -> "view::Console": DisplayInstructions()
"controller::Application" -> "view::Console": GetEvent()
"controller::Application" -> "controller::Member": ListMemberInfo()
"controller::Member" -> "view::Console": WantsToLookAtMemberInfo()
"view::Console" -> "view::Console": GetPersonalNumber()
"controller::Member" -> "model::Database": GetMember(memberPNum)

alt Member exist = true
    "controller::Member" -> "view::Console": ListMemberInfo(choosenMember)
else Member exist = false
    "controller::Member" -> "view::Console": MemberDoesNotExist()
end
@enduml
